language: java
sudo: false
before_install:
- cd etc/build
script: ant war
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/draw.war
  skip_cleanup: true
  on:
    repo: scoutzfiction/drawio   
